# Generated by Django 4.2.5 on 2023-11-30 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_tbl_user_user_type_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='id',
        ),
        migrations.AlterField(
            model_name='seller',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
