# Generated by Django 4.2.5 on 2024-02-12 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_cart_items_cart_remove_cart_items_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_firstname', models.CharField(max_length=100)),
                ('seller_lastname', models.CharField(max_length=100)),
                ('seller_phone', models.CharField(max_length=15)),
                ('seller_address', models.CharField(max_length=255)),
                ('seller_pincode', models.CharField(max_length=10)),
                ('seller_district', models.CharField(max_length=100)),
                ('seller_state', models.CharField(max_length=100)),
                ('seller_brand_name', models.CharField(max_length=255)),
                ('seller_business_address', models.CharField(max_length=255)),
                ('seller_gst_number', models.CharField(max_length=15)),
                ('seller_pan_number', models.CharField(max_length=15)),
                ('seller_bank_name', models.CharField(max_length=100)),
                ('seller_bank_account_number', models.CharField(max_length=50)),
                ('seller_ifsc_code', models.CharField(max_length=20)),
                ('admin_approval', models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='pending', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
