# Generated by Django 4.2.5 on 2024-02-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_tbl_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_seller',
            name='seller_license_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tbl_seller',
            name='seller_license_pdf',
            field=models.FileField(null=True, upload_to='certificates/'),
        ),
    ]
