# Generated by Django 4.2.5 on 2024-02-12 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_tbl_seller_seller_license_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_seller',
            name='seller_business_address',
        ),
    ]
