# Generated by Django 4.2.5 on 2024-02-19 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_tbl_seller_seller_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=20)),
                ('category_description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_colour',
            fields=[
                ('colour_id', models.AutoField(primary_key=True, serialize=False)),
                ('colour_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_current_price', models.IntegerField()),
                ('product_about_product', models.CharField(max_length=200)),
                ('product_material', models.CharField(max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tbl_category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tbl_seller')),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_size',
            fields=[
                ('size_id', models.AutoField(primary_key=True, serialize=False)),
                ('size_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_stock',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_quantity', models.IntegerField()),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tbl_colour')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tbl_product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tbl_size')),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_ProductImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tbl_product')),
            ],
        ),
    ]
