# Generated by Django 4.2.5 on 2024-02-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_tbl_category_tbl_colour_tbl_product_tbl_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_seller',
            name='seller_license_pdf',
            field=models.FileField(null=True, upload_to='seller_certificates/'),
        ),
    ]
