# Generated by Django 4.2.5 on 2024-02-20 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_tbl_seller_seller_license_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_category',
            name='category_description',
        ),
    ]
