# Generated by Django 4.2.5 on 2024-02-23 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_tbl_category_category_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_seller',
            old_name='admin_approval',
            new_name='seller_admin_approval',
        ),
        migrations.AddField(
            model_name='tbl_seller',
            name='seller_form_filled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Tbli_tailor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tailor_firstname', models.CharField(max_length=100, null=True)),
                ('tailor_lastname', models.CharField(max_length=100, null=True)),
                ('tailor_pan_number', models.CharField(max_length=15, null=True)),
                ('tailor_phone', models.CharField(max_length=15, null=True)),
                ('tailor_address', models.CharField(max_length=255, null=True)),
                ('tailor_pincode', models.CharField(max_length=10, null=True)),
                ('tailor_district', models.CharField(max_length=100, null=True)),
                ('tailor_state', models.CharField(max_length=100, null=True)),
                ('tailor_brand_name', models.CharField(max_length=255, null=True)),
                ('tailor_license_number', models.CharField(default='', max_length=50)),
                ('tailor_license_pdf', models.FileField(null=True, upload_to='tailor_certificates/')),
                ('tailor_gst_number', models.CharField(max_length=15, null=True)),
                ('tailor_bank_name', models.CharField(max_length=100, null=True)),
                ('tailor_bank_account_number', models.CharField(max_length=50, null=True)),
                ('tailor_ifsc_code', models.CharField(max_length=20, null=True)),
                ('tailor_admin_approval', models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='pending', max_length=10)),
                ('tailor_form_filled', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
