# Generated by Django 4.2.5 on 2024-02-23 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_rename_admin_approval_tbl_seller_seller_admin_approval_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tbli_tailor',
            new_name='Tbl_tailor',
        ),
    ]
