# Generated by Django 4.2.5 on 2024-02-27 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_rename_tbli_tailor_tbl_tailor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_seller',
            old_name='seller_admin_approval',
            new_name='admin_approval',
        ),
    ]
