# Generated by Django 4.2.5 on 2024-03-06 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_tbl_cart_tbl_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_cartitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='tbl_cartitem',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='tbl_cartitem',
            name='user',
        ),
        migrations.AddField(
            model_name='tbl_cartitem',
            name='cart_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tbl_cartitem',
            name='cart_stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.tbl_stock'),
        ),
        migrations.AlterField(
            model_name='tbl_cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tbl_cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tbl_cart'),
        ),
    ]
