# Generated by Django 4.2.5 on 2024-03-06 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_tbl_cartitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_cartitem',
            name='cart_price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tbl_cartitem',
            name='cart_quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tbl_cartitem',
            name='cart_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tbl_stock'),
        ),
    ]
