# Generated by Django 4.2.5 on 2024-03-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_tbl_cartitem_cart_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_cartitem',
            name='cart_price',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
