# Generated by Django 4.2.5 on 2024-03-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_tbl_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_payment',
            name='payment_method',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tbl_payment',
            name='transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
