# Generated by Django 4.2.5 on 2024-03-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_tbl_order_tbl_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=20)),
            ],
        ),
    ]
