# Generated by Django 4.2.5 on 2024-03-18 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_tbl_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_product',
            name='brand_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.tbl_brand'),
        ),
        migrations.AlterField(
            model_name='tbl_brand',
            name='brand_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tbl_brand',
            name='brand_name',
            field=models.CharField(max_length=100),
        ),
    ]
