# Generated by Django 4.2.5 on 2024-03-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_tbl_product_brand_name_alter_tbl_brand_brand_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_brand',
            name='brand_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
