# Generated by Django 4.2.5 on 2024-04-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_tbl_tailor_tailor_brand_logo_tbl_tailordemoproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_tailor',
            name='tailor_bank_branch',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
