# Generated by Django 4.2.5 on 2024-04-05 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_tbl_tailor_tailor_bank_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_tailor',
            old_name='tailor_admin_approval',
            new_name='admin_approval',
        ),
    ]
