# Generated by Django 4.2.5 on 2024-04-14 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_rename_tailor_admin_approval_tbl_tailor_admin_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_measurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bust_size', models.FloatField(blank=True, null=True)),
                ('waist_size', models.FloatField(blank=True, null=True)),
                ('hip_size', models.FloatField(blank=True, null=True)),
                ('shoulder_size', models.FloatField(blank=True, null=True)),
                ('inseam', models.FloatField(blank=True, null=True)),
                ('sleeve_length', models.FloatField(blank=True, null=True)),
                ('neck_width', models.FloatField(blank=True, null=True)),
                ('arm_size', models.FloatField(blank=True, null=True)),
                ('upper_body_length', models.FloatField(blank=True, null=True)),
                ('neck_depth', models.FloatField(blank=True, null=True)),
                ('arm_length', models.FloatField(blank=True, null=True)),
                ('arm_design', models.FloatField(blank=True, null=True)),
                ('tailor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tailor_measurements', to='users.tbl_tailor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
