# Generated by Django 4.2.5 on 2024-04-14 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_tbl_measurements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_measurements',
            old_name='arm_design',
            new_name='armhole_depth',
        ),
    ]
