# Generated by Django 4.2.5 on 2024-04-17 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_rename_arm_design_tbl_measurements_armhole_depth'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('viewed', models.BooleanField(default=False)),
                ('send_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
                ('tailor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='users.tbl_tailor')),
            ],
        ),
    ]
